
# Site settings
title: BAOBAB
subtitle: Unit
baseurl: #baobab
url: # https://neurospin.github.io/

# Contacts
email: jean-francois.mangin@cea.fr
author:
street_address:
city:
state: 
zip_code:
country: France
phone:

# Expiration in days
expiration_opportunities: 100
expiration_news: 300

# Social settings
#500px_url: http://www.neurospin-wiki.org/pmwiki/Main/DirectionsToNeurospin
#facebook_url: https://www.facebook.com/pages/NeuroSpin/171075046414933
#github_url: https://github.com/neurospin
#twitter_url: https://twitter.com/neurospin_91
#youtube_url: https://www.youtube.com/CEASaclay
map_url: https://www.google.fr/maps/@48.720535,2.1467526,16z?hl=en

# Sass building
sass:
    sass_dir: _sass
    
# Build settings
markdown: kramdown

# Collections
collections_dir: _collections
collections:

  labs:
    output    : true
    permalink : /labs/:title/index.html
